// src/data/data.jsx

export const doctors = [
    {
      id: 1,
      name: "dr. Aditya Wirawan",
      price: "Rp14.900",
      specialty: "Umum",
      rating: "95%",
      reviews: "5,1rb",
      image: "https://randomuser.me/api/portraits/men/32.jpg",
      status: "Chat Sekarang",
    },
    {
      id: 2,
      name: "dr. Tanti Mariana, SpOG",
      price: "Rp49.000",
      oldPrice: "Rp79.000",
      specialty: "Kandungan",
      rating: "97%",
      reviews: "8,2rb",
      image: "https://randomuser.me/api/portraits/women/65.jpg",
      status: "Online",
    },
    {
      id: 3,
      name: "dr. I Kadek Serisana Wasita, Sp.A",
      price: "Rp49.000",
      oldPrice: "Rp79.000",
      specialty: "Anak",
      rating: "96%",
      reviews: "6,9rb",
      image: "https://randomuser.me/api/portraits/men/45.jpg",
      status: "Online",
    },
    {
      id: 4,
      name: "dr. Andi Syafrina, Sp.KK",
      price: "Rp59.000",
      oldPrice: "Rp89.000",
      specialty: "Kulit",
      rating: "94%",
      reviews: "4,3rb",
      image: "https://randomuser.me/api/portraits/women/70.jpg",
      status: "Online",
    },
    {
      id: 5,
      name: "drg. Rendra Mahesa",
      price: "Rp39.000",
      specialty: "Gigi",
      rating: "92%",
      reviews: "2,1rb",
      image: "https://randomuser.me/api/portraits/men/29.jpg",
      status: "Online",
    },
    {
      id: 6,
      name: "dr. Mita Astuti, M.Psi",
      price: "Rp49.000",
      specialty: "Psikolog",
      rating: "98%",
      reviews: "7,8rb",
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      status: "Online",
    },
    {
      id: 7,
      name: "dr. Daniel Kusuma",
      price: "Rp19.000",
      specialty: "Umum",
      rating: "90%",
      reviews: "3,7rb",
      image: "https://randomuser.me/api/portraits/men/10.jpg",
      status: "Chat Sekarang",
    },
    {
      id: 8,
      name: "drg. Maria Lestari",
      price: "Rp42.000",
      specialty: "Gigi",
      rating: "91%",
      reviews: "1,8rb",
      image: "https://randomuser.me/api/portraits/women/25.jpg",
      status: "Online",
    }
  ];  
  
  export const categories = ["Semua", "Umum", "Anak", "Kandungan", "Kulit", "Gigi", "Psikolog"];
  